stages:
  - build
  - test
  - deploy
  
maven-build:
  image: maven:3-jdk-11
  stage: build
  script: "mvn package -B"

maven-test:
  image: maven:3-jdk-11
  stage: test
  script: "mvn test -B"

deploy:
  stage: deploy
  image: ruby:latest
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=commande-authorization-server --api-key=997c6806-a2c8-4a6f-ab99-041920022e3d
  only:
  - master  
  
